theme = "downtown_funk"

[editor]
true-color = true
undercurl = true
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]

[editor.soft-wrap]
enable = true

[keys.normal]
D = "delete_selection_noyank"

