[[language]]
name = "rust"

[[language]]
name = "markdown"
language-servers = ["mdpls"]

[[language]]
name = "nix"
formatter = { command = "alejandra" }
auto-format = true

[language-server.rust-analyzer.config]
cargo.features = "all"
check.command = "clippy"

[language-server.mdpls]
command = "mdpls"

[language-server.mdpls.config]
markdown.preview.auto = true
markdown.preview.browser = ["firefox", "-P", "local_server"]
