[[language]]
name = "rust"

[language.config.check]
command = "clippy"

[language.config.cargo]
features = "all"

[[language]]
name = "markdown"
language-server = { command = "mdpls" }
config = { markdown.preview.auto = true, markdown.preview.browser = ["firefox", "-P", "local_server"] }

[[language]]
name = "nix"
formatter = { command = "alejandra" }
auto-format = true
